### PR TITLE
Misc. minor improvements

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by yevster** [comment]
What's the value of adding the Travis CI config? I don't want to keep CI system descriptors for every CI tool every consumer might use.

**Comment by yevster** [comment]
Cherry-picked all commits except ced4a09857b46c57b9875a0ba04e99ebb4699e60.

**Comment by sschuberth** [comment]
In case you haven't noticed yet, Travis CI is pretty much *the* standard CI tool to integrate with at GitHub (when building for Linux or Mac; for Windows use AppVeyor). In constrast to Jenkins CI et al., it's a hosted service that's free for Open Source projects. You just need to sign-up with your GitHub account. So it's not about what a customer might use internally, but what the community uses.

**Comment by sschuberth** [comment]
@yevster Have you made up your mind about integrating with Travis CI? One of the main benefits I forgot to mention is that is will check PRs to build / pass tests, too.

**Comment by yevster** [comment]
@sschuberth, yes - this is just an API and all the tests are unit tests. There are no "integration tests" in this project to speak of, so I see no benefit in Continuous Integration in this case.

**Comment by sschuberth** [comment]
@yevster Like I said, the benefit would be that you immediately see whether the code in a PR actually builds and whether it breaks any unit tests. You can run any tests (or in fact any commands) as part of a Travis CI build, it's not limited to "integration tests".

**Comment by sschuberth** [comment]
As an example, [this](https://github.com/sschuberth/spdxtra/pull/1) is how the check for a PR that breaks a test would look like. The red cross next to a commit marks the failure.

**Comment by yevster** [comment]
Alright, I'll merge it in - can always take it out if it proves unnecessary.

**Comment by sschuberth** [comment]
Thanks. I'll do a new PR based on current master with some minor improvements to the `.travis.yml` file.

**Comment by sschuberth** [comment]
See https://github.com/yevster/spdxtra/pull/7. For some reason Travis CI did not seem to start building that PR yet, though. Have you enabled the spdxtra project in the Travis CI web UI?

**Comment by yevster** [comment]
Yes, I have. Not sure myself why it's not building. It hasn't built yet.

**Pull request closed without merging**
